-- Enable Row-Level Security on every public table.
-- No policies are defined, so RLS denies ALL access via the Supabase anon/
-- authenticated (PostgREST) roles, closing the Data-API exposure. The app's
-- Prisma connection uses the 'postgres' role (BYPASSRLS), so it is unaffected.

ALTER TABLE "AdminUser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AnalyticsEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseStatusEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClassificationBatch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailChangeToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GicnProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LeadMagnetSubscriber" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MagicLinkToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Participant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Position" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Program" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProgramRegistration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecoveryComplaint" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Referral" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SavedClassification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SavedRoadmap" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ScholarshipAward" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Sponsorship" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffClassification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UploadedDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Webhook" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WebhookDelivery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
