-- AlterTable
ALTER TABLE "WebhookDelivery" ALTER COLUMN "lastAttemptAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "nextAttemptAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);
